export const SHOW_LOADER_FORECAST = 'APP/SHOW_LOADER_FORECAST';
export const SHOW_LOADER_PAST = 'APP/SHOW_LOADER_PAST';
export const HIDE_LOADER_FORECAST = 'APP/HIDE_LOADER_FORECAST';
export const HIDE_LOADER_PAST = 'APP/HIDE_LOADER_PAST';

export const FETCH_7DAYSFORECAST = 'FETCH_7DAYSFORECAST';
export const FETCH_PAST_FORECAST = 'FETCH_PAST_FORECAST';

export const GET_DATE = 'GET_DATE';
export const GET_LOCATION = 'GET_LOCATION';
